#-*- encoding:utf-8 -*-
from hello import CompetitionClass,db
db.session.add(CompetitionClass(CCname='教育部“互联网+创新创业大赛”'))
db.session.add(CompetitionClass(CCname='挑战杯”全国大学生创业计划大赛'))
db.session.add(CompetitionClass(CCname='辽宁省大学生创业计划大赛'))
db.session.add(CompetitionClass(CCname='机械创新设计'))
db.session.add(CompetitionClass(CCname='市场调查分析'))
db.session.add(CompetitionClass(CCname='计算机设计'))
db.session.add(CompetitionClass(CCname='结构设计'))
db.session.add(CompetitionClass(CCname='广告艺术'))
db.session.add(CompetitionClass(CCname='西门子中国制造挑战赛'))
db.session.add(CompetitionClass(CCname='化工设计'))
db.session.add(CompetitionClass(CCname='电子设计'))
db.session.add(CompetitionClass(CCname='机器人'))
db.session.add(CompetitionClass(CCname='移动应用开发'))
db.session.add(CompetitionClass(CCname='网络商务创新应用'))
db.session.add(CompetitionClass(CCname='模拟法庭'))
db.session.add(CompetitionClass(CCname='物理实验'))
db.session.add(CompetitionClass(CCname='英语演讲'))
db.session.add(CompetitionClass(CCname='智慧经济'))
db.session.add(CompetitionClass(CCname='导游大赛'))
db.session.add(CompetitionClass(CCname='护理技能'))
db.session.add(CompetitionClass(CCname='测绘地理'))
db.session.add(CompetitionClass(CCname='工程训练综合能力'))
db.session.add(CompetitionClass(CCname='动植物标本'))
db.session.commit()
