#-*- encoding:utf-8 -*-
from hello import db,Project_mode
db.session.add(Project_mode(status='等待指导教师审核'))
db.session.add(Project_mode(status='等待学院管理员审核'))
db.session.add(Project_mode(status='等待大创中心审核'))
db.session.add(Project_mode(status='待提交中期报告'))
db.session.add(Project_mode(status='等待指导教师中期审核'))
db.session.add(Project_mode(status='等待学院中期审核'))
db.session.add(Project_mode(status='等待大创中心中期审核'))
db.session.add(Project_mode(status='待提交结题报告'))
db.session.add(Project_mode(status='等待指导教师结题审核'))
db.session.add(Project_mode(status='等待学院结题审核'))
db.session.add(Project_mode(status='等待大创中心结题审核'))
db.session.add(Project_mode(status='结题'))
db.session.commit()