#-*- encoding:utf-8 -*-
from hello import CompetitionClass,AwardLevel,AwardGrade,db,Major,Collage,User_mode,Project_mode,User
db.session.add(CompetitionClass(CCname='教育部“互联网+创新创业大赛”'))
db.session.add(CompetitionClass(CCname='挑战杯”全国大学生创业计划大赛'))
db.session.add(CompetitionClass(CCname='辽宁省大学生创业计划大赛'))
db.session.add(CompetitionClass(CCname='机械创新设计'))
db.session.add(CompetitionClass(CCname='市场调查分析'))
db.session.add(CompetitionClass(CCname='计算机设计'))
db.session.add(CompetitionClass(CCname='结构设计'))
db.session.add(CompetitionClass(CCname='广告艺术'))
db.session.add(CompetitionClass(CCname='西门子中国制造挑战赛'))
db.session.add(CompetitionClass(CCname='化工设计'))
db.session.add(CompetitionClass(CCname='电子设计'))
db.session.add(CompetitionClass(CCname='机器人'))
db.session.add(CompetitionClass(CCname='移动应用开发'))
db.session.add(CompetitionClass(CCname='网络商务创新应用'))
db.session.add(CompetitionClass(CCname='模拟法庭'))
db.session.add(CompetitionClass(CCname='物理实验'))
db.session.add(CompetitionClass(CCname='英语演讲'))
db.session.add(CompetitionClass(CCname='智慧经济'))
db.session.add(CompetitionClass(CCname='导游大赛'))
db.session.add(CompetitionClass(CCname='护理技能'))
db.session.add(CompetitionClass(CCname='测绘地理'))
db.session.add(CompetitionClass(CCname='工程训练综合能力'))
db.session.add(CompetitionClass(CCname='动植物标本'))
db.session.add(AwardLevel(ALname='省级A类'))
db.session.add(AwardLevel(ALname='省级B类'))
db.session.add(AwardLevel(ALname='国家级A类'))
db.session.add(AwardLevel(ALname='国家级B类'))
db.session.add(AwardLevel(ALname='国家级C类'))
db.session.add(AwardLevel(ALname='国际级'))
db.session.add(AwardGrade(AGname='三等奖'))
db.session.add(AwardGrade(AGname='二等奖'))
db.session.add(AwardGrade(AGname='一等奖'))
db.session.add(AwardGrade(AGname='特等奖'))
db.session.commit()
f= open('major.txt', 'rt',encoding="utf-8")
for x in f:
    db.session.add(Major(mname=x[:-1]))
db.session.commit()
f.close()
f= open('collage.txt','rt',encoding="utf-8")
for x in f:
 db.session.add(Collage(cname=x[:-1]))
db.session.commit()
f.close()
judge = User_mode(name='学生')
manager = User_mode(name='管理员')
student = User_mode(name='教师用户')
proleader = User_mode(name='学院管理员')
db.session.add(judge)
db.session.add(manager)
db.session.add(student)
db.session.add(proleader)
db.session.commit()
pro = Project_mode.query.filter_by(status='结题').first()
if not pro:
    db.session.add(Project_mode(status='等待指导教师审核'))
    db.session.add(Project_mode(status='等待学院管理员审核'))
    db.session.add(Project_mode(status='等待大创中心审核'))
    db.session.add(Project_mode(status='待提交中期报告'))
    db.session.add(Project_mode(status='等待指导教师中期审核'))
    db.session.add(Project_mode(status='等待学院中期审核'))
    db.session.add(Project_mode(status='等待大创中心中期审核'))
    db.session.add(Project_mode(status='待提交结题报告'))
    db.session.add(Project_mode(status='等待指导教师结题审核'))
    db.session.add(Project_mode(status='等待学院结题审核'))
    db.session.add(Project_mode(status='等待大创中心结题审核'))
    db.session.add(Project_mode(status='结题'))
    db.session.commit()
pro = Project_mode.query.filter_by(status='结题审核失败').first()
if not pro:
    db.session.add(Project_mode(status='立项审核失败'))
    db.session.add(Project_mode(status='中期审核失败'))
    db.session.add(Project_mode(status='结题审核失败'))
    db.session.commit()
db.session.add(User(username='001',password='001',usermode=2))
db.session.commit()



