"""initial migration

Revision ID: d9e84cf6582a
Revises: 
Create Date: 2017-09-01 11:40:03.030347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e84cf6582a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BusinessPlan',
    sa.Column('BusinessPlanId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('remarks', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('BusinessPlanId')
    )
    op.create_table('Project_mode',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('status')
    )
    op.create_table('ResultsType',
    sa.Column('Rid', sa.Integer(), nullable=False),
    sa.Column('Rname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('Rid')
    )
    op.create_table('Website',
    sa.Column('WebId', sa.Integer(), nullable=False),
    sa.Column('website', sa.String(length=64), nullable=True),
    sa.Column('remarks', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('WebId')
    )
    op.create_table('collage',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('cname', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('cid'),
    sa.UniqueConstraint('cname')
    )
    op.create_table('funds',
    sa.Column('Fid', sa.Integer(), nullable=False),
    sa.Column('FundingUse', sa.Text(), nullable=True),
    sa.Column('Amount', sa.Integer(), nullable=True),
    sa.Column('Pid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Fid')
    )
    op.create_table('major',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('mname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('mid'),
    sa.UniqueConstraint('mname')
    )
    op.create_table('other',
    sa.Column('OtherId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('remarks', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('OtherId')
    )
    op.create_table('paper',
    sa.Column('paperId', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('JournalName', sa.String(length=64), nullable=True),
    sa.Column('remarks', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('paperId')
    )
    op.create_table('patent',
    sa.Column('patentId', sa.Integer(), nullable=False),
    sa.Column('patentName', sa.String(length=64), nullable=True),
    sa.Column('person', sa.String(length=64), nullable=True),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('remarks', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('patentId')
    )
    op.create_table('project',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('Pname', sa.String(length=64), nullable=False),
    sa.Column('Plevel', sa.String(length=64), nullable=True),
    sa.Column('Pclass', sa.String(length=64), nullable=True),
    sa.Column('Collage', sa.String(length=64), nullable=True),
    sa.Column('Person_in_charge', sa.Integer(), nullable=True),
    sa.Column('Teacher', sa.String(length=64), nullable=True),
    sa.Column('Forteacher', sa.String(length=64), nullable=True),
    sa.Column('Describe', sa.Text(), nullable=True),
    sa.Column('Status', sa.Integer(), nullable=True),
    sa.Column('StartDate', sa.String(length=64), nullable=True),
    sa.Column('PlanDate', sa.String(length=64), nullable=True),
    sa.Column('MidSubdate', sa.String(length=64), nullable=True),
    sa.Column('EndSubdate', sa.String(length=64), nullable=True),
    sa.Column('EndDate', sa.String(length=64), nullable=True),
    sa.Column('ReassonsForApplication', sa.String(length=64), nullable=True),
    sa.Column('ProjectPlan', sa.String(length=64), nullable=True),
    sa.Column('Innovate', sa.Text(), nullable=True),
    sa.Column('Schedule', sa.Text(), nullable=True),
    sa.Column('Budget', sa.Integer(), nullable=True),
    sa.Column('BudgetPlan', sa.Text(), nullable=True),
    sa.Column('ExpectedResults', sa.Text(), nullable=True),
    sa.Column('TeaStarOpinion', sa.Text(), nullable=True),
    sa.Column('CollStarOpinion', sa.Text(), nullable=True),
    sa.Column('SchStarOpinion', sa.Text(), nullable=True),
    sa.Column('MidProgress', sa.Text(), nullable=True),
    sa.Column('MidResults', sa.Text(), nullable=True),
    sa.Column('TeaMidOpinion', sa.Text(), nullable=True),
    sa.Column('DCCenterMidOpinion', sa.Text(), nullable=True),
    sa.Column('SchMidOpinion', sa.Text(), nullable=True),
    sa.Column('ResultsDescribe', sa.Text(), nullable=True),
    sa.Column('ResultsType', sa.Integer(), nullable=True),
    sa.Column('ResultsSummary', sa.Text(), nullable=True),
    sa.Column('ResultsNum', sa.Integer(), nullable=True),
    sa.Column('Problems', sa.Text(), nullable=True),
    sa.Column('TeaEndOpinion', sa.Text(), nullable=True),
    sa.Column('DCCenterEndOpinion', sa.Text(), nullable=True),
    sa.Column('Achievement', sa.String(length=64), nullable=True),
    sa.Column('doc', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('report',
    sa.Column('reportId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('remarks', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('reportId')
    )
    op.create_table('user_mode',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('mid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('collage', sa.String(length=64), nullable=True),
    sa.Column('major', sa.String(length=64), nullable=True),
    sa.Column('tel', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('usermode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usermode'], ['user_mode.mid'], ),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('User_Project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['project.pid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User_Project')
    op.drop_table('user')
    op.drop_table('user_mode')
    op.drop_table('report')
    op.drop_table('project')
    op.drop_table('patent')
    op.drop_table('paper')
    op.drop_table('other')
    op.drop_table('major')
    op.drop_table('funds')
    op.drop_table('collage')
    op.drop_table('Website')
    op.drop_table('ResultsType')
    op.drop_table('Project_mode')
    op.drop_table('BusinessPlan')
    # ### end Alembic commands ###
